# Generated by Django 2.2.9 on 2021-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211207_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pushToken',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=25, null=True, unique=True),
        ),
    ]
