# Generated by Django 3.2.12 on 2022-05-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
