# Generated by Django 3.2.12 on 2022-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_user_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_links',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
