# Generated by Django 3.2.12 on 2022-03-28 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(default='', max_length=50)),
                ('sender_type', models.CharField(default='', max_length=50)),
                ('receiver_id', models.CharField(default='', max_length=50)),
                ('viewed', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject_line', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=1000)),
                ('sender_delete', models.BooleanField(default=False)),
                ('receiver_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('member_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagegroupm1', to=settings.AUTH_USER_MODEL)),
                ('member_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagegroupm2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
